# Generated by Django 4.1.1 on 2022-11-16 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OP', 'open'), ('CL', 'closed'), ('PA', 'paid'), ('SH', 'shipped')], default='OP', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('products', models.TextField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=30)),
                ('first_name', models.TextField(blank=True, max_length=30)),
                ('last_name', models.TextField(blank=True, max_length=30)),
                ('street', models.TextField(blank=True, max_length=30)),
                ('street_number', models.IntegerField(null=True)),
                ('zip', models.IntegerField(null=True)),
                ('city', models.TextField(blank=True, max_length=30)),
                ('country', models.TextField(blank=True, max_length=30)),
                ('phone', models.TextField(blank=True, max_length=30)),
                ('shipping_note', models.TextField(blank=True, max_length=200)),
            ],
        ),
    ]
